build:
  dostuff:
    image: node:8
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm i
      - npm run preversion
      - npm run prepublish

cache:
  mount:
    - /drone/.npm
